### ISSUE TITLE
Issue converting a phyloseq into a phylosip object 

### ISSUE THREAD

**Issue by dennismetze** [bramstone/qsip#2]
Hi Bram, 

I tried to convert a phyloseq object into a phylosip object as described in the README. 
It seemed to work fine but when I try to use `plot(phylosip_object)`, I get the following error: 

```
Error in .valueClassTest(ans, c("data.frame", "phyloseq", "phylosip"), : 
c("invalid value from generic function ‘plot_curve’, class “gg”, expected “data.frame” or “phyloseq” or “phylosip”", "invalid value from generic function ‘plot_curve’, class “ggplot”, expected “data.frame” or “phyloseq” or “phylosip”")
```

Also, when I check the phylosip object via `phylosip_object`, the number of qSIP measures is zero. 

This is the code I used: 

```
dat <- specify_qsip(dat1,density = "Density",
                    abund ='GCNs',
                    rep_id ='SoilID',
                    rep_num = 'Replicate',
                    rep_group ='Treatment',
                    iso ='18O',
                    iso_trt ='Isotope',
                   timepoint ='Timepoint')
```
The parameters correspond with variables in `sam_data(dat1)`. 

Thanks for making this package available.

**Comment by bramstone** [comment]
Hi Dennis,

My apologies for creating what is, essentially, an unfinished function. Your specify_qsip() step has created the correct data in the correct form but I have had trouble getting the plotting method to create density curves the same way across different data sets.

I'm in the process of overhauling the calculations to be more flexible to different types of experimental designs and will largely use functionality from the data.table package. This is basically a conversion of the entire codebase. Until then, I am reaching out to you via email to send you some of the data.table code as I make the transition.

For now, I'll leave the issue open so anyone else experience the problem may comment and get in touch with me.

**Comment by bramstone** [comment]
Closing this issue as we transition towards a new workflow that is independent from the phyloseq functionality
